### ISSUE TITLE
Could nasbench2_pred.py be run on multiple GPUs?

### ISSUE THREAD

**Issue by zhengyuntao123** [SamsungLabs/zero-cost-nas#12]

**Comment by zhengyuntao123** [comment]
I find `parser.add_argument('--gpu', type=int, default=0, help='GPU index to work on')` in nasbench2_pred.py. But could I run it on multiple GPUs in order to save time?

**Comment by vaenyr** [comment]
You could manually run different comments with different `--gpu`, `--start` and `--enc`.
