### ISSUE TITLE
May I ask how the project can be transformed according to its own network?

### ISSUE THREAD

**Issue by qq272574497** [SamsungLabs/zero-cost-nas#13]
Can I just replace my own network to apply my own network?
net = nasbench2.get_model_from_arch_str(arch_str, get_num_classes(args))

**Comment by vaenyr** [comment]
We cannot guarantee that our implementation will work flawlessness with any network, but the idea is that the `net_orig` parameter (i.e., the first one) to `find_measures` can be any network - just create your and pass to the function together with the intended loss function and input batch, and it should do the rest.

**Comment by qq272574497** [comment]
In Nasbench2_pred.py, the value of accuracy was found to depend on the data in NAS-Bench-201-v1_0-E61699.pth. As mentioned in the paper, is synflow used as the fitness to measure the  framework?

**Comment by vaenyr** [comment]
I'm sorry, I don't understand your question - also, it seems you have created another issue for it, does it mean this one can be closed?
