### ISSUE TITLE
The fitness in nasbench2_pred.py

### ISSUE THREAD

**Issue by qq272574497** [SamsungLabs/zero-cost-nas#14]
In Nasbench2_pred.py, the value of accuracy was found to depend on the data in NAS-Bench-201-v1_0-E61699.pth. As mentioned in the paper, is synflow used as the fitness to measure the framework?

**Comment by vaenyr** [comment]
I'm sorry, I don't understand your question. If you can, please clarify the following:
1. what do you mean by "was found to depend on data in"? for nasbench201 accuracy of models is queried from the precomputed values released with the benchmark (that is, so the file you mentioned).
2. what do you mean by "fitness to measure the framework"? synflow is one of the zero-cost proxies that we study, that approximate accuracy of different networks. We report correlation (in the sense of produced rankings) of per-network scores produced by synflow (among other functions) to accuracy of the same networks obtained by querying nasbench201 benchmark data.

**Comment by qq272574497** [comment]
> 2\. synflow
hi,
can  I filter the network using synflow as an fitness for the network? Instead of accuracy or error

**Comment by vaenyr** [comment]
Yes, it is meant to replace accuracy as a way of scoring networks

**Comment by qq272574497** [comment]
> Yes, it is meant to replace accuracy as a way of scoring networks

thanks!!!!!!!,this is a good paper

**Comment by qq272574497** [comment]
> synflow
hi，
The bigger the synflow, the better???

**Comment by qq272574497** [comment]
> Yes, it is meant to replace accuracy as a way of scoring networks

hi,
   The bigger the synflow, the better????

**Comment by vaenyr** [comment]
Yes.
