### ISSUE TITLE
About the ImageNet1k datasets

### ISSUE THREAD

**Issue by December-boy** [SamsungLabs/zero-cost-nas#3]
Hi, thanks for the nice work. I would like to ask how to get 'imageNet-train-256. h5' and' imageNet-val-256. h5' in imageNet1k.

 elif dataset == 'ImageNet1k':
        train_dataset = H5Dataset(os.path.join(datadir, 'imagenet-train-256.h5'), transform=train_transform)
        test_dataset  = H5Dataset(os.path.join(datadir, 'imagenet-val-256.h5'),   transform=test_transform)

**Comment by mohsaied** [comment]
We converted ImageNet to HDF5 because that runs faster on our system, but you can replace those lines with the standard:

```
train_dataset = torchvision.datasets.ImageFolder(root=os.path.join(datadir, 'train'), transform=train_transform)
test_dataset = torchvision.datasets.ImageFolder(root=os.path.join(datadir, 'val'), transform=test_transform)
```

feel free to do a pull request with this if you would like to add the option to our repo -- we'll appreciate it!
