### ISSUE TITLE
pickle file used in nas_examples.ipynb

### ISSUE THREAD

**Issue by chenwydj** [SamsungLabs/zero-cost-nas#6]
Thank you very much for this great work!

In [nas_examples.ipynb](https://github.com/SamsungLabs/zero-cost-nas/blob/main/notebooks/nas_examples.ipynb), you pre-computed the scores (`synflow_proxy`) and stored in `nb2_cf100_seed42_dlrandom_dlinfo1_initwnone_initbnone.p` for the `zero_cost_warmup`.

To run your notebook, would you mind sharing this pre-computed `synflow_proxy` score file?

Thank you!

**Comment by mohsaied** [comment]
Yep. There's a drive link in the readme :)

**Comment by chenwydj** [comment]
@mohsaied Thank you very much!!
